repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: "\\.idea/(.)*"
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "test_*"
        args: ["-iii", "-ll", "-s=B308,B703"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-bugbear,
            flake8-comprehensions,
            flake8-mutable,
            flake8-print,
            flake8-simplify,
          ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        entry: poetry run pylint --extension-pkg-whitelist="pydantic" main.py
        exclude: "^(alembic|tests).*$"
        types: [python]
        require_serial: true
        pass_filenames: false
      - id: mypy
        name: mypy
        language: system
        entry: poetry run mypy .
        types: [python]
        pass_filenames: false
